#pragma once

enum PacketType : uint32_t {
    HANDSHAKE = 0, LOGIN = 1, LOGIN_SUCCESS = 2, LOGIN_ERROR = 3, REGISTER = 4, REGISTER_SUCCES = 5, REGISTER_ERROR = 6,
    DISCONNECT = 7, START_FRENDLY_QUEUE = 8, START_RANKED_QUEUE = 9, CANCEL_QUEUE = 10, START_GAME = 11, RANKING_SCORE = 12
};