#pragma once

enum PacketType : uint32_t {
    HANDSHAKE = 0, LOGIN = 1, LOGIN_SUCCESS = 2, LOGIN_ERROR = 3, REGISTER = 4, REGISTER_SUCCESS = 5, REGISTER_ERROR = 6,
    DISCONNECT = 7, START_QUEUE = 8, CANCEL_QUEUE = 9, START_GAME = 10, ASK_MAP = 11, RECEIVE_MAP = 12, START_QUEUE_RESULT = 13, CANCEL_QUEUE_RESULT = 14, START_UDP_GAME = 15,
    SEND_POSITION = 16, ACK = 17
};