#pragma once

enum PacketType : uint32_t {
    HANDSHAKE = 0, LOGIN = 1, LOGIN_SUCCESS = 2, LOGIN_ERROR = 3, REGISTER = 4, REGISTER_SUCCES = 5, REGISTER_ERROR = 6,
    DISCONNECT = 7, START_FRENDLY_QUEUE = 8, CANCEL_QUEUE = 9, START_GAME = 10, ASK_MAP = 11, RECEIVE_MAP = 12
};